### PR TITLE
Tilt, offset, graphics, button positions, custom width.

### PR DESCRIPTION
**Pull request by chylek**
This PR unfortunately adds many things. I just couldn't stop myself and do it properly in mulltiple PRs. Sorry.

- adds support for shutters with tilt (#32)
- adds support for shutters with offset (related to #24, #60 and PR #27)
- adds optional shortcut button for closing/opening to predefined position 
- adds graphics to visualize when the shutters are opening/closing
- adds translated labels to most of the buttons
- allows buttons to be at the top/bottom of the shutter graphic (#25)
- allows customizing the width of the shutter visualization (#10, #6)
- adds option to disable up/down buttons when in opened/closed state (respectively)

### CODE REVIEW

**Comment by chylek** [comment]
This is what it looks like when tilt, custom width and buttons on bottom are configured. The text on the rights ays the shutters have been closed. This is configurable, there can still be percentage as before.

image

This is what it looks like when offset, buttons on bottom and shortcut to partially closed position are configured.
You can see the "have been closed" text is accompanied by percentage. Because offset was defined, this percentage shows how much movement there is left until the shutters are fully closed. (because the offset has been reached, you see the shutters closed in the visualization). 

image

**Comment by Xyaren** [comment]
Amazing!
Looks really good to me!

**Comment by chylek** [comment]
@Xyaren thanks for the bug report. Should be fixed. 

Also the option to disable the buttons is there now, check the readme.

**Comment by patrix252** [comment]
I was checking the code and I saw that you documented the attribute `tilt` on the readme, when instead the attribute name is `can_tilt`

**Comment by Xyaren** [comment]
@Deejayfool any reason this is not merged ?

**Comment by Deejayfool** [comment]
The only reason is the time :) .
As soon as I'll be able to check it and try it, I'll consider merging it.

**Comment by PatrickOnGit** [comment]
> The only reason is the time :) .
> As soon as I'll be able to check it and try it, I'll consider merging it.

Hi Deejayfool
I know, time is a precious thing.
Do you have an idea when you would find some to test and merge the PR?
You both spend so much time in this, so it would be nice if we can use it.

Thank you very much

**Review by Deejayfool — COMMENTED** [review]
Accepted pull request

**Comment by Jack77777777** [comment]
Hi Guys,
I have the Homematic HmIP-DRBLI4 to control my venetian blinds. When i set `tilt: true` there are no arrows in the card to control tilt. When i click on the name of the shutter you can see there are tilt´s which can be controlled here.
image
image

**Comment by chylek** [comment]
@Jack77777777 use `can_tilt: true`

**Comment by Jack77777777** [comment]
@chylek got it. I was using your fork and after merge changed to the roiginal from [Deejayfool](https://github.com/Deejayfool) and was not awrae tilt was changed to can_tilt. It´s working now. Thanks a lot.

**Comment by Jack77777777** [comment]
@chylek I have one more question. How can i set that the tilt opens or closes only 50% when using this buttons ?
image

**Comment by chylek** [comment]
@Jack77777777 I don't think you will be able to do that using this card. Maybe create a separate button card that calls the "Cover: Set tilt position" service.

**Comment by Jack77777777** [comment]
> @Jack77777777 I don't think you will be able to do that using this card. Maybe create a separate button card that calls the "Cover: Set tilt position" service.

I will donit this way then. 
Thanks

**Comment by archont00** [comment]
Fibaro FGR-223 has separate entities for opening/closing the ventian blinds (cover.fgr_223_switch_01) and for setting the tilt (cover.fgr_223_switch_01_2).

I use Z-Wave JS, entities were created automatically.

Is there a way to setup the card to use a different entity id for the tilt?

**Pull request merged**
