### PR TITLE
Add configurable offset (e.g. for german shutter)

### PR DESCRIPTION
**Pull request by MaxWinterstein**
In Germany 🇩🇪 (and maybe some other countries too?) we call our shutter/cover/blinds _*Rollladen*_, and they seem to behave a little differently. 
If you never saw the german version, here is a quick video: https://youtu.be/PCudaPpwoAM?t=76

To sum it up, when the _Rollladen_ is closing, and touching the bottom position, it is not completely closed. The elements (_Rollladenstäbe_) are loosely connected and allow some light to get through (_Lichtschlitze_). After some additional movement in the closing direction, manually via a Belt (_Gurtband_) or electrical, it closes completely.

As the wife was complaining the Window (_Fenster_) was not looking like the real window I came up with this fix.

Also requested here: https://github.com/Deejayfool/hass-shutter-card/issues/24

### CODE REVIEW

**Comment by dabepp** [comment]
So is there a chance this gets into the main branch? I would love to see this! :-) (Or am I just too stupid to use it?)

**Comment by MaxWinterstein** [comment]
> So is there a chance this gets into the main branch? I would love to see this! :-) (Or am I just too stupid to use it?)

You can manually overwrite the `hass-shutter-card.js` with my version and should be good to go until it gets merged. 

this is my version:  https://raw.githubusercontent.com/MaxWinterstein/hass-shutter-card/master/hass-shutter-card.js

No idea how your setup is, if you have the *Visual Studio Code* Add-on available it should be easy.Just open the file

image

**Comment by Sangoku** [comment]
I was planing to write somthing like this :D Thanks a bunch.

**Comment by GreXoR1** [comment]
Hey,
I copied your version using visual code but it's not working for me. Am I using it wrong?

```
type: custom:shutter-card
title: Roleta
entities:
  - entity: cover.curtain_switch_curtain
    name: Testna roleta
    buttons_position: left
    invert_percentage: true
    offset: 15

```
roleta

**Comment by Pascal3366** [comment]
Why is this not getting merged ?

**Comment by Deejayfool** [comment]
Feature added with Pull Request #69

**Pull request closed without merging**
